grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 2
    verbose: 5
model_selection:
  module_0:
    class: XGBRegressor
    module: xgboost
    params:
      learning_rate: 0.1
      max_depth: 2
      n_estimators: 1000
    search_param_grid:
      learning_rate:
        - 0.1
        - 0.2
        - 0.3
      max_depth:
        - 2
        - 4
        - 6
      n_estimators:
        - 600
        - 800
        - 1000
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      criterion: 'squared_error'
      max_depth: 20.0
      n_estimators: 100
    search_param_grid:
      n_estimators:
        - 100
        - 500
        - 1000
      max_depth:
        - 12
        - 16
        - 20
        - 24
      criterion:
        - "squared_error"
        - "absolute_error"