FileName: "Concrete_Data.csv"
Number_of_Columns: 9
ColumnNames:
  Cement (component 1)(kg in a m^3 mixture): float
  Blast Furnace Slag (component 2)(kg in a m^3 mixture): float
  Fly Ash (component 3)(kg in a m^3 mixture): float
  Water  (component 4)(kg in a m^3 mixture): float
  Superplasticizer (component 5)(kg in a m^3 mixture): float
  Coarse Aggregate  (component 6)(kg in a m^3 mixture): float
  Fine Aggregate (component 7)(kg in a m^3 mixture): float
  Age (day): int
  Concrete compressive strength(MPa, megapascals) : float