FileName: "Concrete_Data.csv"
Number_of_Columns: 9
ColumnNames:
  Cement: float
  Blast_Furnace_Slag: float
  Fly_Ash: float
  Water: float
  Superplasticizer: float
  Coarse_Aggregate: float
  Fine_Aggregate: float
  Age_in_days: int
  Concrete_Strength: float
